### PR TITLE
A small Hacker News reader.

### PR DESCRIPTION
**Pull request by bvanderveen**
Demonstrates:
- usage in a controller with retain/targets/cancel
- global error notification

### CODE REVIEW

**Comment by nfarina** [comment]
Dude, very cool, works great! Merged.

**Comment by bvanderveen** [comment]
Thanks. Just realized I missed [super dealloc] in ItemController. Not sure it's worth a pull request but you might want to add that. ;)

**Comment by nfarina** [comment]
Gotcha, will fix shortly. Would you mind if I removed the submodule dependency and included SMXmlDocument.m directly in the sample project directory? I love submodules personally but folks always come back to me saying something is broken when they just forgot to tend to the submodules.

**Comment by bvanderveen** [comment]
Yeah, go for it.

**Pull request merged**
